const socialLinks={instagram:"https://instagram.com/yourusername",github:"https://github.com/yourusername",linkedin:"https://linkedin.com/in/yourusername",facebook:"https://facebook.com/yourusername",twitter:"https://x.com/yourusername",youtube:"https://youtube.com/@yourusername",snapchat:"https://snapchat.com/add/yourusername",leetcode:"https://leetcode.com/u/yourusername/",codechef:"https://codechef.com/users/yourusername",hackerrank:"https://hackerrank.com/yourusername",geeksforgeeks:"https://geeksforgeeks.org/user/yourusername",discord:"#",telegram:"https://t.me/yourusername",whatsapp:"https://wa.me/91XXXXXXXXXX",email:"mailto:your@email.com"};
const socialMeta={instagram:["fa-brands fa-instagram","Instagram"],github:["fa-brands fa-github","GitHub"],linkedin:["fa-brands fa-linkedin-in","LinkedIn"],facebook:["fa-brands fa-facebook-f","Facebook"],twitter:["fa-brands fa-x-twitter","Twitter/X"],youtube:["fa-brands fa-youtube","YouTube"],snapchat:["fa-brands fa-snapchat","Snapchat"],leetcode:["fa-solid fa-code","LeetCode"],codechef:["fa-solid fa-code","CodeChef"],hackerrank:["fa-brands fa-hackerrank","HackerRank"],geeksforgeeks:["fa-solid fa-laptop-code","GeeksforGeeks"],discord:["fa-brands fa-discord","Discord"],telegram:["fa-brands fa-telegram","Telegram"],whatsapp:["fa-brands fa-whatsapp","WhatsApp"],email:["fa-solid fa-envelope","Email"]};
function renderSocials(){["heroSocial","footerSocial"].forEach(id=>{const el=document.getElementById(id);if(!el)return;const keys=id==="footerSocial"?["instagram","github","linkedin","youtube","twitter","leetcode"]:Object.keys(socialLinks);el.innerHTML=keys.map(k=>`<a class="social-icon" href="${socialLinks[k]}" target="_blank" rel="noopener noreferrer" title="${socialMeta[k][1]}" aria-label="${socialMeta[k][1]}"><i class="${socialMeta[k][0]}"></i></a>`).join("")});document.querySelectorAll("[data-social]").forEach(a=>a.href=socialLinks[a.dataset.social])}
const skills=[["HTML5","fa-brands fa-html5",92],["CSS3","fa-brands fa-css3-alt",88],["JavaScript","fa-brands fa-js",85],["React","fa-brands fa-react",78],["Responsive Design","fa-solid fa-mobile-screen-button",90],["Node.js","fa-brands fa-node-js",75],["Express.js","fa-solid fa-server",72],["MongoDB","fa-solid fa-database",70],["Git & GitHub","fa-brands fa-github",82],["Postman","fa-solid fa-paper-plane",75]];
function renderSkills(){document.getElementById("skillsGrid").innerHTML=skills.map(s=>`<article class="skill-card reveal"><div class="skill-head"><b><i class="${s[1]}"></i>${s[0]}</b><span>${s[2]}%</span></div><div class="bar"><i data-width="${s[2]}%"></i></div></article>`).join("")}
const projects=[
{id:1,title:"ExamSathi — Exam Preparation Platform",cat:["Frontend","JavaScript","Full Stack"],desc:"An exam preparation platform with study material, mock tests, search, dashboards and interactive learning features.",img:"assets/project-1.jpg",tags:["HTML","CSS","JavaScript","Node.js"],github:"https://github.com/yourusername/examsathi",live:"#",features:["Study material and mock tests","Search and filtering","Responsive student dashboard"]},
{id:2,title:"Student Management System",cat:["JavaScript","Full Stack"],desc:"A practical management platform for handling student records and administrative workflows.",img:"assets/project-2.jpg",tags:["HTML","CSS","JavaScript","Express.js","MongoDB"],github:"https://github.com/yourusername/student-management",live:"#",features:["Student CRUD operations","Admin workflow","MongoDB data storage"]},
{id:3,title:"Movie Website",cat:["Frontend","React"],desc:"A modern movie discovery interface powered by the TMDB API.",img:"assets/project-3.jpg",tags:["React.js","TMDB API","CSS"],github:"https://github.com/yourusername/movie-app",live:"#",features:["Movie search","Categories and details","Responsive UI"]},
{id:4,title:"Task Management Dashboard",cat:["Frontend","JavaScript"],desc:"A productivity dashboard for tasks, progress reports and visual analytics.",img:"assets/project-1.jpg",tags:["HTML","CSS","JavaScript","Chart.js"],github:"https://github.com/yourusername/task-dashboard",live:"#",features:["Task management","Daily/monthly reports","Interactive charts"]}];
function renderFilters(){const cats=["All","Frontend","JavaScript","React","Full Stack"];document.getElementById("projectFilters").innerHTML=cats.map((c,i)=>`<button class="filter-btn ${i===0?"active":""}" data-filter="${c}">${c}</button>`).join("")}
function renderProjects(filter="All"){const list=filter==="All"?projects:projects.filter(p=>p.cat.includes(filter));document.getElementById("projectsGrid").innerHTML=list.map(p=>`<article class="project-card reveal"><div class="project-image"><img src="${p.img}" alt="${p.title}" loading="lazy"></div><div class="project-body"><h3>${p.title}</h3><p>${p.desc}</p><div class="tag-list">${p.tags.map(t=>`<span class="tag">${t}</span>`).join("")}</div><div class="project-actions"><a class="btn btn-secondary" href="${p.github}" target="_blank" rel="noopener">GitHub</a><a class="btn btn-primary" href="${p.live}" target="_blank" rel="noopener">Live Demo</a><button class="text-btn view-project" data-id="${p.id}">View Details →</button></div></div></article>`).join("");observeReveals()}
const services=[["fa-solid fa-code","Web Development","Modern responsive websites with clean, maintainable code."],["fa-solid fa-palette","Frontend Development","Interactive UI using HTML, CSS and JavaScript."],["fa-brands fa-react","React Development","Modern React applications with reusable components."],["fa-solid fa-server","Backend Development","Node.js and Express.js APIs for practical web apps."],["fa-solid fa-cloud-arrow-up","Website Deployment","Deploy projects using GitHub, Vercel and similar platforms."],["fa-solid fa-pen-ruler","Website UI Design","Modern responsive interfaces focused on usability."]];
function renderServices(){document.getElementById("servicesGrid").innerHTML=services.map(s=>`<article class="service-card reveal"><div class="service-icon"><i class="${s[0]}"></i></div><h3>${s[1]}</h3><p>${s[2]}</p></article>`).join("")}
const coding=[["fa-brands fa-github","GitHub","100+","Open Profile","github"],["fa-solid fa-code","LeetCode","500+","Problems","leetcode"],["fa-solid fa-code","CodeChef","3★","Rating","codechef"],["fa-brands fa-hackerrank","HackerRank","5★","Skills","hackerrank"],["fa-solid fa-laptop-code","GeeksforGeeks","100+","Problems","geeksforgeeks"]];
function renderCoding(){document.getElementById("codingGrid").innerHTML=coding.map(c=>`<article class="coding-card reveal"><i class="${c[0]}"></i><h3>${c[1]}</h3><strong>${c[2]}</strong><p>${c[3]}</p><a href="${socialLinks[c[4]]}" target="_blank" rel="noopener">View Profile →</a></article>`).join("")}
const achievements=[["fa-solid fa-code","100+ Coding Problems Solved"],["fa-solid fa-laptop-code","10+ Projects Completed"],["fa-solid fa-certificate","Web Development Certification"],["fa-solid fa-trophy","Hackathon Participation"],["fa-solid fa-code-branch","Open Source Contributions"],["fa-solid fa-rocket","Continuous Learning"]];
function renderAchievements(){document.getElementById("achievementGrid").innerHTML=achievements.map(a=>`<article class="achievement-card reveal"><i class="${a[0]}"></i><h3>${a[1]}</h3><p>Replace this placeholder with your real milestone or result.</p></article>`).join("")}
function renderStats(){const stats=[["10+","Projects"],["5+","Technologies"],["500+","Problems Solved"],["1+","Years Learning"]];document.getElementById("stats").innerHTML=stats.map(s=>`<div class="stat-card"><strong>${s[0]}</strong><span>${s[1]}</span></div>`).join("")}
function renderContributions(){const g=document.getElementById("contributionGrid");for(let i=0;i<260;i++)g.innerHTML+=`<i title="Contribution"></i>`}
const testimonials=[["Priya Sharma","Project Collaborator","Vishal is consistent, curious and focused on building useful experiences.","assets/profile.jpg"],["Rahul Singh","Developer Friend","A strong learner who keeps improving his coding and problem-solving skills.","assets/profile.jpg"],["Amit Verma","Mentor","Vishal approaches projects with a practical mindset and attention to detail.","assets/profile.jpg"]];
let testIndex=0;
function renderTestimonial(){const t=testimonials[testIndex];document.getElementById("testimonialCard").innerHTML=`<img src="${t[3]}" alt="${t[0]}"><div class="stars">★★★★★</div><h3>${t[0]}</h3><small>${t[1]}</small><p>“${t[2]}”</p>`;document.getElementById("testimonialDots").innerHTML=testimonials.map((_,i)=>`<span class="dot ${i===testIndex?"active":""}"></span>`).join("")}
function openProject(id){const p=projects.find(x=>x.id===id);document.getElementById("modalImage").src=p.img;document.getElementById("modalImage").alt=p.title;document.getElementById("modalTitle").textContent=p.title;document.getElementById("modalDescription").textContent=p.desc;document.getElementById("modalFeatures").innerHTML=`<ul>${p.features.map(f=>`<li>${f}</li>`).join("")}</ul>`;document.getElementById("modalTags").innerHTML=p.tags.map(t=>`<span class="tag">${t}</span>`).join("");document.getElementById("modalGithub").href=p.github;document.getElementById("modalLive").href=p.live;document.getElementById("projectModal").classList.add("open")}
function showToast(msg){const t=document.getElementById("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2800)}
function observeReveals(){document.querySelectorAll(".reveal:not(.observed)").forEach(el=>{el.classList.add("observed");revealObserver.observe(el)})}
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");const bar=e.target.querySelector(".bar i");if(bar)bar.style.width=bar.dataset.width}}),{threshold:.12});
function typeEffect(){


    const words=["Full Stack Developer","Your next level starts with one line of code" , "Think. Code. Create. ", "Dream in ideas, build in code."];



    let wi=0,ci=0,del=false;const el=document.getElementById("typing");function tick(){const word=words[wi];el.textContent=word.slice(0,ci);if(!del){ci++;if(ci>word.length){del=true;return setTimeout(tick,1100)}}else{ci--;if(ci===0){del=false;wi=(wi+1)%words.length}}setTimeout(tick,del?45:85)}tick()}
function scrollUI(){const y=window.scrollY,h=document.documentElement.scrollHeight-innerHeight;document.getElementById("scrollProgress").style.width=(y/h*100)+"%";document.getElementById("navbar").classList.toggle("scrolled",y>20);document.getElementById("backTop").classList.toggle("show",y>500);document.querySelectorAll("section[id]").forEach(s=>{if(y>=s.offsetTop-120){document.querySelectorAll(".nav-link").forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+s.id))}})}
document.addEventListener("DOMContentLoaded",()=>{renderSocials();renderSkills();renderFilters();renderProjects();renderServices();renderCoding();renderAchievements();renderStats();renderContributions();renderTestimonial();typeEffect();observeReveals();setTimeout(()=>document.getElementById("loader").classList.add("hide"),600);if(localStorage.getItem("theme")==="light")document.body.classList.add("light")});
window.addEventListener("scroll",scrollUI);
document.getElementById("menuToggle").addEventListener("click",()=>{const n=document.getElementById("navMenu"),open=n.classList.toggle("open");document.getElementById("menuToggle").setAttribute("aria-expanded",open)});
document.querySelectorAll(".nav-link").forEach(a=>a.addEventListener("click",()=>document.getElementById("navMenu").classList.remove("open")));
document.getElementById("themeToggle").addEventListener("click",()=>{document.body.classList.toggle("light");localStorage.setItem("theme",document.body.classList.contains("light")?"light":"dark")});
document.getElementById("projectFilters").addEventListener("click",e=>{if(e.target.classList.contains("filter-btn")){document.querySelectorAll(".filter-btn").forEach(b=>b.classList.remove("active"));e.target.classList.add("active");renderProjects(e.target.dataset.filter)}});
document.getElementById("projectsGrid").addEventListener("click",e=>{const b=e.target.closest(".view-project");if(b)openProject(+b.dataset.id)});
document.getElementById("backTop").addEventListener("click",()=>scrollTo({top:0,behavior:"smooth"}));
document.getElementById("prevTest").addEventListener("click",()=>{testIndex=(testIndex-1+testimonials.length)%testimonials.length;renderTestimonial()});
document.getElementById("nextTest").addEventListener("click",()=>{testIndex=(testIndex+1)%testimonials.length;renderTestimonial()});
setInterval(()=>{testIndex=(testIndex+1)%testimonials.length;renderTestimonial()},6000);
document.querySelectorAll("[data-close]").forEach(b=>b.addEventListener("click",()=>document.getElementById(b.dataset.close).classList.remove("open")));
document.querySelector(".cert-btn").addEventListener("click",()=>{document.getElementById("certificateImage").src=document.querySelector(".cert-btn").dataset.image;document.getElementById("certificateModal").classList.add("open")});
document.querySelectorAll(".modal").forEach(m=>m.addEventListener("click",e=>{if(e.target===m)m.classList.remove("open")}));
document.getElementById("contactForm").addEventListener("submit",e=>{e.preventDefault();const f=e.currentTarget,msg=document.getElementById("formMessage");if(!f.checkValidity()){msg.textContent="Please complete all fields correctly.";msg.className="form-message error";return}const subject=encodeURIComponent(document.getElementById("subject").value);const body=encodeURIComponent(`Name: ${document.getElementById("name").value}\nEmail: ${document.getElementById("email").value}\n\n${document.getElementById("message").value}`);window.location.href=`mailto:your@email.com?subject=${subject}&body=${body}`;msg.textContent="Opening your email client...";msg.className="form-message success";showToast("Email client opened")});
document.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelectorAll(".modal.open").forEach(m=>m.classList.remove("open"))});
if(window.matchMedia("(min-width:1000px)").matches){const dot=document.getElementById("cursorDot"),ring=document.getElementById("cursorRing");window.addEventListener("mousemove",e=>{dot.style.left=e.clientX+"px";dot.style.top=e.clientY+"px";ring.style.left=e.clientX+"px";ring.style.top=e.clientY+"px"})}
const particleBox=document.getElementById("particles");for(let i=0;i<35;i++){const p=document.createElement("i");p.style.left=Math.random()*100+"%";p.style.top=Math.random()*100+"%";p.style.animationDelay=Math.random()*5+"s";p.style.cssText+=`;position:absolute;width:2px;height:2px;border-radius:50%;background:rgba(255,255,255,.35);animation:float ${3+Math.random()*5}s ease-in-out infinite;`;particleBox.appendChild(p)}